In [2]:
# import numpy library

import numpy as np

In [3]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [4]:
print(np.__version__)

2.2.5


In [5]:
# Check the type of the array

type(a)

numpy.ndarray

In [6]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

In [7]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [8]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [9]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

In [10]:
a = np.array([10, 2, 30, 40,50])

a[1] = 20
a


array([10, 20, 30, 40, 50])

In [11]:
a[3]

np.int64(40)

In [12]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [13]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [15]:
print(arr[:4])

[1 2 3 4]


In [16]:
print(arr)

[1 2 3 4 5 6 7]


In [17]:
print(arr[4:])

[5 6 7]


In [18]:
print(arr[1:5:])

[2 3 4 5]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Even numbers
print(arr[1:8:2])

[2 4 6 8]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Odd numbers
print(arr[0:8:2])

[1 3 5 7]


In [21]:
# Create the index list

select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [22]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300, 400])

In [23]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

In [24]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [25]:
# Get the size of numpy array

a.size

5

In [26]:
# Get the number of dimensions of numpy array

a.ndim

1

In [27]:
# Get the shape/size of numpy array

a.shape

(5,)

In [29]:
# Create a numpy array

a = np.array([1, -1, 1, -1])
a

array([ 1, -1,  1, -1])

In [30]:
# Get the mean of numpy array

mean = a.mean()
mean

np.float64(0.0)

In [31]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

np.float64(1.0)

In [32]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [33]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

np.int64(5)

In [1]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

NameError: name 'b' is not defined

In [35]:
c = np.array([-10, 201, 43, 94, 502])

# Enter your code here
sum_c = c.min() + c.max()
sum_c

np.int64(492)

In [36]:
max_c = c.max()
max_c

min_c = c.min()
min_c


Sum = (max_c +min_c)
Sum

np.int64(492)

In [37]:
u = np.array([1, 0])
u

array([1, 0])